### ISSUE TITLE
vite更新页面后，pinia始终获取不到token导致请求头带不了，报token无效， router.replace也没有执行成功

### ISSUE THREAD

**Issue by lichenglong-blog** [biubiubiu01/vue3-basic-admin#1]
![image](https://github.com/biubiubiu01/vue3-basic-admin/assets/24689873/8b9eea4f-bea8-44f5-aaf9-fdf72bb54c53)
![image](https://github.com/biubiubiu01/vue3-basic-admin/assets/24689873/fd766379-8862-4bf5-b164-853e27dd3d3a)
![image](https://github.com/biubiubiu01/vue3-basic-admin/assets/24689873/01e88918-fdc2-462a-941e-fd0c1a34bd19)
缓存里是有token的，在开发中保存代码，每次更新页面，请求接口前，浏览器都获取不到token。
因为获取不了token，接口会报了401，就会退出到登录页面，但是发现vite瞬间更新页面router.replace居然也没生效，router也是有对象是纯在的，也就没办法跳到登录页面。
就是存在两个问题.
大哥咋解决

**Comment by lichenglong-blog** [comment]
@biubiubiu01  大哥

**Comment by biubiubiu01** [comment]
未复现出来，我这边看是可以的，根据你的描述看起来像是热更新的问题，可以删除依赖重新注入看看。
![image](https://github.com/biubiubiu01/vue3-basic-admin/assets/41505007/8c79219f-9fa9-468c-874e-36d2670d76ed)

**Comment by lichenglong-blog** [comment]
应该是vite的热更新造成的，目前用浏览器缓存取token可以，或者不改发版线索不会出现这样的问题
