### ISSUE TITLE
请问table的column如何多个的自定义solt

### ISSUE THREAD

**Issue by lichenglong-blog** [biubiubiu01/vue3-basic-admin#2]
![image](https://github.com/biubiubiu01/vue3-basic-admin/assets/24689873/eec236d1-57f4-413c-a4c5-362a8f897c88)
好像没有生效，我看组件的solt直接定死了name,如果多个自定义solt列就都是一样的，如何改呢，base-table组件到base-page-table组件，要跨越两层组件来做solt，那在base-page-table组件的name如何动态定义呢
`  base-table组件
<template v-if="item.formType === FormTypeEnum.SLOT">
<slot name="tableColumn" :scope="scope" :column="item"></slot>
</template>`

`    base-page-table组件 
<template #tableColumn="{ scope, column }">
                    <slot name="tableColumn" :scope="scope" :column="column"></slot>
                </template>
`
最终到引入base-page-table组件
`页面
<base-page-table>
<template #tableColumn="{ scope, column }">
                </template>
</base-page-table>
`

**Comment by biubiubiu01** [comment]
<template #tableColumn="{ scope, column }">
         <div v-if="column.fieldName === 'xxxx'">
                111
          </div>
  </template>

**Comment by biubiubiu01** [comment]
` <template #tableColumn="{ scope, column }">
        <div v-if="column.fieldName === 'xxxx'">
                  111
         </div>
 </template>`

**Comment by lichenglong-blog** [comment]
> 
了解，感谢

**Comment by lichenglong-blog** [comment]
起作用了，但是那个base-page-table组件还需要加动态的solt name
`  <template #tableColumn="{ scope, column }">
                    <slot :name="column.fieldName" :scope="scope" :column="column"></slot>
                </template>`
![image](https://github.com/biubiubiu01/vue3-basic-admin/assets/24689873/c91e2577-385f-4358-8f98-de2f7858f5b2)

最后这样引入也可以
![image](https://github.com/biubiubiu01/vue3-basic-admin/assets/24689873/03a29774-3cee-4204-869a-049ac4ef6404)

**Comment by biubiubiu01** [comment]
根据个人习惯来，看你自己想用一个插槽然后判断还是多个插槽，这个没啥影响的。
